### ISSUE TITLE
README.md: broken links to the fatturapa.gov.it xsl files

### ISSUE THREAD

**Issue by paride** [Truelite/python-a38#10]
The two `README.md `links to the xsl files from fatturapa.gov.it:

* https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/fatturaordinaria_v1.2.xsl
* https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/fatturapa_v1.2.xsl

are currently broken (404).

**Comment by paride** [comment]
I found new links for updated stylesheets at https://www.fatturapa.gov.it/it/norme-e-regole/documentazione-fattura-elettronica/formato-fatturapa/index.html. They are:

 * https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.1/Foglio_di_stile_fatturaordinaria_v1.2.1.xsl
 * https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.1/Foglio_di_stile_fatturaPA_v1.2.1.xsl

I tried using the "fatturaordinaria" one but unfortunately it didn't work (well, at least not with version 0.1.3, currently in Debian unstable):
```
ERROR uncaught exception
Traceback (most recent call last):
  File "/usr/bin/a38tool", line 350, in <module>
    main()
  File "/usr/bin/a38tool", line 343, in main
    res = app.run()
  File "/usr/bin/a38tool", line 247, in run
    self.render(f, output)
  File "/usr/bin/a38tool", line 288, in render
    self.transform.to_pdf(self.wkhtmltopdf, f, output)
  File "/usr/lib/python3/dist-packages/a38/render.py", line 38, in to_pdf
    raise RuntimeError("%s exited with error %d: stderr: %s", self.wkhtmltopdf, res.returncode, res.stderr)
AttributeError: 'XSLTTransform' object has no attribute 'wkhtmltopdf'
```
OTOH the stylesheet from AssoSoftware works fine.

It would be nice to ship the stylesheets together with this library, however license for the site contents [1] doesn't allow so, and I couldn't find anything more specific for the stylesheets...

[1] https://www.fatturapa.gov.it/it/copyright/index.html

**Comment by spanezz** [comment]
> It would be nice to ship the stylesheets together with this library, however license for the site contents [1] doesn't allow so, and I couldn't find anything more specific for the stylesheets...

Indeed, I couldn't find anything that said I could distribute those files, so I just put links in the README.. which is quite sad.

I'll now fix the README to link to the FatturaPA index page instead of individual stylesheets, since their names, as you have noticed, change with versions

**Comment by spanezz** [comment]
The exception you reported, seems to be fixed in the current main branch
