### ISSUE TITLE
Creating a python package with  `setup.py build sdist` fails

### ISSUE THREAD

**Issue by tschager** [Truelite/python-a38#30]
A package build with

`python setup.py build sdist`

produces the following error when installed using `pip install dist/a38-0.1.5.tar.gz`

```
Processing ./dist/a38-0.1.5.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-krekzuva/setup.py", line 25, in <module>
          install_requires=parse_requirements("requirements-lib.txt"),
        File "/tmp/pip-req-build-krekzuva/setup.py", line 9, in parse_requirements
          line_iter = (line.strip() for line in open(filename))
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements-lib.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tschager** [comment]
I've made a pull request #31 for this issue. Adding requirements-lib.txt to Manifest.in solves the issue

**Comment by valholl** [comment]
Thanks for spotting this!

I've merged the PR
